apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: blacklist
  name: blacklist
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: blacklist
    spec:
      containers:
      - env:
        - name: BLACKLIST
          value: '"169.254.169.254 104.27.149.197"'
        image: blacklisttest:latest
        name: blacklist
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
